version: '3.8'

services:
  api:
    container_name: cloud-file-storage
    image: ghcr.io/martinbarreiroo/cloud-file-storage
    ports:
      - "8000:8080"
    environment:
      DB_USER: ${DB_USER:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-admin}
      DB_NAME: cloud-file-storage-db
      DB_HOST: db
      DB_PORT: 5432
      DOCKER_PORT: 8080
    env_file:
      - .env
    restart: always

  db:
    container_name: cloud-file-storage-db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always