version: '3.8'

services:
  api:
    container_name: cloud-file-storage
    image: ghcr.io/martinbarreiroo/cloud-file-storage
    ports:
      - "8000:8080"
    environment:
      DB_USER: ${DB_USER:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-admin}
      DB_NAME: ${DB_NAME:-cloud-file-storage-db}
      DB_HOST: ${DB_HOST:-localhost}
      DB_PORT: ${DB_PORT:-5432}
      DOCKER_PORT: 8080
    env_file:
      - .env
    restart: always

  db-dev:
    container_name: cloud-file-storage-db-dev
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_DB: ${DB_NAME:-cloud-file-storage-db}
    env_file:
      - .env
    volumes:
      - pgdata-dev:/var/lib/postgresql/cloud-file-storage-data
    restart: always

  db-test:
    container_name: cloud-file-storage-db-test
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_TEST_USER:-test}
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD:-test}
      POSTGRES_DB: ${DB_TEST_NAME:-cloud-file-storage-test}
    env_file:
      - .env.test
      - .env
    volumes:
      - pgdata-test:/var/lib/postgresql/cloud-file-storage-test-data
    restart: always

networks:
  minionetwork:
    driver: bridge

volumes:
  pgdata-dev:
    driver: local
  pgdata-test:
    driver: local