version: '3.8'

services:
  api:
    container_name: cloud-file-storage
    image: ghcr.io/martinbarreiroo/cloud-file-storage
    ports:
      - "8000:8080"
    environment:
      DB_USER: ${DB_USER:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-admin}
      DB_NAME: ${DB_NAME:-cloud-file-storage-db}
      DB_HOST: ${DB_HOST:-localhost}
      DB_PORT: ${DB_PORT:-5432}
      DOCKER_PORT: 8080
    env_file:
      - .env
    restart: always

  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET_NAME}

  db:
    container_name: cloud-file-storage-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_DB: ${DB_NAME:-cloud-file-storage-db}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/cloud-file-storage-data
    restart: always

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local
  pgdata: