name: Main Branch CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Set up test database
        run: docker-compose up db-test -d
      - name: Wait for DB to be ready
        run: sleep 10
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Check formatting
        run: npx prettier --check "src/**/*.ts" "test/**/*.ts"
        
      - name: Run tests
        run: npm test

      - name: Run e2e tests
        run: npm run test:e2e
        
      - name: Build project
        run: npm run build

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Option 1: Use Docker Compose GitHub Action
      - name: Set up Docker Compose
        uses: docker/compose-action@v2
        
      # Option 2: Use Docker CLI with Compose V2 (already installed on GitHub runners)
      - name: Start test database
        run: docker compose up db-test -d
        
      # Option 3: Install Docker Compose explicitly
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      
      - name: Start database with explicit install
        run: docker-compose up db-test -d
        
      # Remaining steps...